# Test values for waldur-site-agent Helm chart
# This file is used for CI/CD testing and as a reference

# Test combination 2: Polling-based processing
agents:
  orderProcess:
    enabled: true
    replicas: 1

  report:
    enabled: true
    replicas: 1

  membershipSync:
    enabled: true
    replicas: 1

  # Event-based processing disabled for this test
  eventProcess:
    enabled: false


# Test configuration
secret:
  create: true
  data:
    config.yaml: |
      sentry_dsn: ""
      timezone: "UTC"
      offerings:
        - name: "Test SLURM Offering"
          waldur_api_url: "http://test-waldur:8081/api/"
          waldur_api_token: "test-token-123"
          waldur_offering_uuid: "test-uuid-123"
          username_management_backend: "base"
          order_processing_backend: "slurm"
          membership_sync_backend: "slurm"
          reporting_backend: "slurm"
          resource_import_enabled: false
          mqtt_enabled: false
          stomp_enabled: false
          websocket_use_tls: true
          backend_type: "slurm"
          backend_settings:
            default_account: "root"
            customer_prefix: "test_"
            project_prefix: "test_"
            allocation_prefix: "test_"
            qos_downscaled: "limited"
            qos_paused: "paused"
            qos_default: "normal"
            enable_user_homedir_account_creation: false
            homedir_umask: "0700"
          backend_components:
            cpu:
              limit: 10
              measured_unit: "k-Hours"
              unit_factor: 60000
              accounting_type: "usage"
              label: "CPU"
            mem:
              limit: 10
              measured_unit: "gb-Hours"
              unit_factor: 61440
              accounting_type: "usage"
              label: "RAM"

# Test with reduced resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Enable health checks for testing
healthCheck:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 30
