"""Translate Waldur (Resource, ResourceProject, [UserRole]) into a ManagedRancherProject CR spec.

Pure functions only — no I/O. The backend module wires this into the
Kubernetes client and the Waldur API client.
"""

from string import Template
from typing import Any, Optional

CRD_API_VERSION = "waldur.io/v1alpha1"
CRD_KIND = "ManagedRancherProject"
CRD_PLURAL = "managedrancherprojects"
CRD_SHORT_PLURAL = "mrp"

# Kubernetes object names: max 253 chars (RFC 1123 subdomain).
MAX_K8S_NAME_LENGTH = 253
# We reserve 9 chars for "-" + 8-hex UUID prefix in the truncation path.
NAME_SUFFIX_RESERVE = 9

# Keycloak's GROUP.NAME column is varchar(255). Names of 256+ chars are
# rejected at create time with HTTP 500 (unhandled DataException in the
# server). We raise at render time instead so the operator never even
# tries to apply such a CR -- the failure mode "your group name template
# combined with these slugs is too long" is much clearer surfaced as a
# plugin-side ValueError than as a downstream operator/Keycloak crash.
# Verified empirically against Keycloak 26 -- 255 OK, 256+ HTTP 500.
MAX_KEYCLOAK_GROUP_NAME_LENGTH = 255


def cr_name(resource_slug: str, resource_project_uuid: str) -> str:
    """Build the metadata.name for a ManagedRancherProject CR.

    Format: ``<resource.slug>-<rp.uuid[:8]>``. Both inputs are
    immutable in Waldur, so the CR identity is stable across renames.
    The 8-char UUID prefix gives ~4 billion combinations per resource
    — collision-free in practice.

    Resource slugs are auto-generated by Waldur and already RFC-1123
    compliant; we lowercase + truncate defensively.
    """
    safe = resource_slug.lower().strip("-")
    suffix = resource_project_uuid.replace("-", "")[:8]
    name = f"{safe}-{suffix}"
    if len(name) > MAX_K8S_NAME_LENGTH:
        # Truncate the slug, never the suffix — keep identity stable.
        name = f"{safe[: MAX_K8S_NAME_LENGTH - NAME_SUFFIX_RESERVE]}-{suffix}"
    return name


def render_group_name(
    template: str,
    *,
    cluster_id: str,
    role_name: str,
    rp_uuid: str = "",
    rp_uuid_short: str = "",
    project_name: str = "",
    customer_slug: str = "",
    project_slug: str = "",
    resource_slug: str = "",
) -> str:
    """Render a Keycloak group name template.

    Supports the following template variables:

    Identifiers (stable, immutable):

    - ``${cluster_id}`` — Rancher cluster ID (e.g. ``c-m-glwxdksp``).
    - ``${rp_uuid}``   — Waldur ResourceProject UUID, full 32-char hex.
    - ``${rp_uuid_short}`` — first 8 hex chars of ``rp_uuid``. Same
      convention as :func:`cr_name`; ~4 billion combinations is more
      than enough within a ``(cluster, role)`` tuple, where the
      relevant collision domain is at most a few dozen RPs.
    - ``${role_name}`` — Waldur role name (pre-mapping).

    Human-readable Waldur-side identifiers (stable but mutable -- can
    change if an admin renames the customer / project / resource in
    Waldur, which would orphan the previously-named Keycloak group):

    - ``${customer_slug}`` — Waldur Customer slug (organization).
    - ``${project_slug}``  — Waldur Project slug (the parent project
      that owns the Resource, NOT the ResourceProject which has no slug).
    - ``${resource_slug}`` — Waldur Resource slug (1:1 with the
      Rancher cluster, so equivalent to ``cluster_id`` semantically
      but human-readable instead of opaque).
    - ``${project_name}`` — human-readable project name (may contain
      spaces; not URL-safe; included for legacy templates).

    The default template (set in :func:`build_cr_spec`) includes
    ``${rp_uuid}`` so each (cluster x project x role) triple gets its
    OWN group. Without ``${rp_uuid}`` (or an equivalent per-project
    discriminator like ``${rp_uuid_short}``), N CRs sharing a
    (cluster, role) pair would all reference the same Keycloak group,
    and:

    - the operator's per-CR member-sync would thrash that group as it
      processed each CR in turn, AND
    - because Rancher binds the SAME group to N project PRTBs,
      granting a user role on project A would also grant the same
      role on B, C, … — collapsing per-project access into per-cluster.

    Custom templates that omit a per-project token are technically
    accepted (the renderer just substitutes whatever variables it
    knows), but the resulting CRs will collide as above. Stick with
    the default unless you have a strong reason.

    A recommended human-readable opt-in template that still keeps
    per-RP uniqueness:

        c_${cluster_id}_${customer_slug}_${project_slug}_${rp_uuid_short}_${role_name}

    Switching templates after deployment leaves the previously-named
    Keycloak groups orphaned (the operator adopts groups by name and
    never renames or deletes adopted groups); plan accordingly.
    """
    rendered = Template(template).safe_substitute(
        cluster_id=cluster_id,
        role_name=role_name,
        rp_uuid=rp_uuid,
        rp_uuid_short=rp_uuid_short,
        project_name=project_name,
        customer_slug=customer_slug,
        project_slug=project_slug,
        resource_slug=resource_slug,
    )
    if len(rendered) > MAX_KEYCLOAK_GROUP_NAME_LENGTH:
        msg = (
            f"Rendered Keycloak group name is {len(rendered)} chars; "
            f"Keycloak's GROUP.NAME column is varchar({MAX_KEYCLOAK_GROUP_NAME_LENGTH}) "
            f"and rejects longer names. Template: {template!r}; "
            f"first 80 chars of result: {rendered[:80]!r}. "
            f"Switch to ${{rp_uuid_short}} (8 chars) instead of ${{rp_uuid}} "
            f"(32 chars), or shorten Waldur slugs / role names."
        )
        raise ValueError(msg)
    return rendered


def build_role_bindings(
    user_roles: list[dict],
    *,
    cluster_id: str,
    group_name_template: str,
    role_map: dict[str, str],
    keycloak_use_user_id: bool = False,
    rp_uuid: str = "",
    rp_uuid_short: str = "",
    project_name: str = "",
    customer_slug: str = "",
    project_slug: str = "",
    resource_slug: str = "",
) -> list[dict]:
    """Group UserRoles by role name and emit one roleBinding per group.

    ``user_roles`` is a list of dicts shaped like the Waldur
    ``marketplace_provider_resources_team_list`` response — each entry
    must have ``role_name`` and a user identifier (``user_uuid`` or
    ``user_username``).

    Roles that aren't present in ``role_map`` are skipped with no error
    — the operator can't bind them anyway. Caller may log this.

    ``rp_uuid`` and ``project_name`` are passed through to the group
    name template so the rendered group name can be unique per RP
    (recommended -- see :func:`render_group_name` docstring).

    Default identifier is the Waldur username, matched against the
    Keycloak username. The UUID path (``keycloak_use_user_id=True``) is
    kept as an opt-in for the niche case where Waldur's user UUID was
    seeded from the Keycloak OIDC ``sub`` claim AND the deployment
    really wants UUID-keyed group membership; for self-hosted Waldur
    where users were created locally, the default username path is the
    only thing that works because the Waldur UUID is unrelated to any
    Keycloak identity.
    """
    by_role: dict[str, list[dict]] = {}
    for ur in user_roles:
        role = ur.get("role_name")
        if not role or role not in role_map:
            continue
        by_role.setdefault(role, []).append(ur)

    bindings: list[dict] = []
    for role_name in sorted(by_role):
        members = [
            {
                "userIdentifier": ident,
                "lookupByID": keycloak_use_user_id,
            }
            for ur in by_role[role_name]
            if (ident := (ur.get("user_uuid") if keycloak_use_user_id else ur.get("user_username")))
        ]
        if not members:
            continue
        bindings.append(
            {
                "groupName": render_group_name(
                    group_name_template,
                    cluster_id=cluster_id,
                    role_name=role_name,
                    rp_uuid=rp_uuid,
                    rp_uuid_short=rp_uuid_short,
                    project_name=project_name,
                    customer_slug=customer_slug,
                    project_slug=project_slug,
                    resource_slug=resource_slug,
                ),
                "rancherRole": role_map[role_name],
                "members": members,
            },
        )
    return bindings


def build_cr_spec(
    *,
    resource: dict,
    resource_project: dict,
    user_roles: list[dict],
    backend_settings: dict,
    cluster_user_roles: Optional[list[dict]] = None,
) -> dict[str, Any]:
    """Assemble the full CR body (apiVersion + kind + metadata + spec).

    Caller is responsible for setting metadata.namespace from config
    when invoking the K8s API.

    Cluster ID resolution: each Waldur Resource is 1:1 with a Rancher
    downstream cluster, so ``resource["backend_id"]`` IS the cluster
    ID. A resource with an empty ``backend_id`` is a configuration
    bug (the offering owner forgot to set the cluster); raise
    KeyError rather than silently emitting an invalid CR.

    ``cluster_user_roles`` are the Resource-scope user roles (from
    ``marketplace_provider_resources_list_users_list``). When provided
    *and* ``backend_settings["cluster_role_map"]`` is non-empty, the
    CR carries a ``spec.cluster.keycloak.roleBindings`` block that
    drives operator-side CRTBs. Without either, the cluster section
    is omitted -- old operators (pre-0.4.0) reject any unknown spec
    field, so emitting an empty placeholder block would break them.
    """
    cluster_id = resource.get("backend_id")
    if not cluster_id:
        msg = (
            f"Cannot determine cluster_id for CR: resource "
            f"'{resource.get('slug') or resource.get('uuid')}' has empty "
            "backend_id. Set the Rancher cluster ID as the resource's "
            "backend_id (each Waldur Resource = one Rancher cluster)."
        )
        raise KeyError(msg)

    rp_uuid = resource_project.get("uuid", "")
    # Same 8-char convention as cr_name (4B combos, collision-free in
    # practice within a (cluster, role) tuple). Lets opt-in templates
    # like c_${cluster_id}_${customer_slug}_${project_slug}_${rp_uuid_short}_${role_name}
    # stay short while remaining unique per RP.
    rp_uuid_short = rp_uuid.replace("-", "")[:8]
    project_name = resource_project.get("name", "")

    # Slugs from the Resource (not the ResourceProject -- RPs have no
    # slug). project_slug here means the Waldur PARENT project that
    # owns the resource, not the ResourceProject inside it.
    customer_slug = resource.get("customer_slug", "") or ""
    project_slug = resource.get("project_slug", "") or ""
    resource_slug = resource.get("slug", "") or ""

    parent_group = render_group_name(
        backend_settings.get("parent_group_name", "c_${cluster_id}"),
        cluster_id=cluster_id,
        role_name="",
        customer_slug=customer_slug,
        project_slug=project_slug,
        resource_slug=resource_slug,
    )
    # Default child template includes ${rp_uuid} so each (cluster x
    # project x role) gets its own Keycloak group -- see
    # render_group_name docstring for why.
    group_template = backend_settings.get(
        "group_name_template", "c_${cluster_id}_${rp_uuid}_${role_name}"
    )
    role_map = backend_settings.get("role_map", {})

    # cr_name is reused as the CR's metadata.name so the
    # (resource, resource-project) identity is encoded in one stable
    # place; pull_resource uses it to look the CR back up by name.
    cr_metadata_name = cr_name(resource["slug"], rp_uuid)

    # spec.namespace was removed in operator 0.3.0 -- the operator no
    # longer creates or owns downstream namespaces. Namespace lifecycle
    # is now a user concern via Rancher; do NOT re-add this field
    # without first restoring namespace handling on the operator side.
    spec: dict[str, Any] = {
        "clusterId": cluster_id,
        "projectName": resource_project["name"],
        "resourceUuid": resource["uuid"],
        "resourceProjectUuid": rp_uuid,
        "keycloak": {
            "enabled": True,
            "parentGroupName": parent_group,
            "roleBindings": build_role_bindings(
                user_roles,
                cluster_id=cluster_id,
                group_name_template=group_template,
                role_map=role_map,
                keycloak_use_user_id=backend_settings.get("keycloak_use_user_id", False),
                rp_uuid=rp_uuid,
                rp_uuid_short=rp_uuid_short,
                project_name=project_name,
                customer_slug=customer_slug,
                project_slug=project_slug,
                resource_slug=resource_slug,
            ),
        },
    }

    cluster_role_map = backend_settings.get("cluster_role_map") or {}
    if cluster_role_map and cluster_user_roles is not None:
        # Cluster-scope groups have NO per-RP discriminator -- one group
        # per (cluster, role) is the desired sharing model, since the
        # operator de-duplicates the underlying CRTB by (clusterId,
        # principal, role). The literal "cluster" segment guards
        # against collisions with the project-scope template, which
        # always contains an rp_uuid hex prefix.
        cluster_group_template = backend_settings.get(
            "cluster_group_name_template", "c_${cluster_id}_cluster_${role_name}"
        )
        cluster_bindings = build_role_bindings(
            cluster_user_roles,
            cluster_id=cluster_id,
            group_name_template=cluster_group_template,
            role_map=cluster_role_map,
            keycloak_use_user_id=backend_settings.get("keycloak_use_user_id", False),
            rp_uuid="",
            rp_uuid_short="",
            project_name="",
            customer_slug=customer_slug,
            project_slug=project_slug,
            resource_slug=resource_slug,
        )
        # Always emit the spec.cluster block when cluster_role_map is
        # configured -- even with an empty roleBindings list. The
        # operator's _gc_orphan_cluster_bindings reads the desired
        # set from spec to decide what to delete, so an empty list is
        # the explicit "no cluster bindings desired" signal it needs.
        spec["cluster"] = {
            "keycloak": {
                "enabled": True,
                "roleBindings": cluster_bindings,
            },
        }

    quotas = _build_resource_quotas(resource_project.get("limits") or {})
    if quotas:
        spec["resourceQuotas"] = quotas

    description = resource_project.get("description")
    if description:
        spec["description"] = description

    return {
        "apiVersion": CRD_API_VERSION,
        "kind": CRD_KIND,
        "metadata": {
            "name": cr_metadata_name,
            # Labels enable orphan-CR pruning in pull_resource: when
            # an RP is removed from Waldur, its CR no longer matches
            # the current set of expected names but is still selectable
            # by the resource-uuid label.
            "labels": {
                "waldur.io/resource-uuid": resource["uuid"],
                "waldur.io/resource-project-uuid": resource_project["uuid"],
            },
        },
        "spec": spec,
    }


_WALDUR_QUOTA_KEYS = {"cpu", "memory", "storage", "gpu"}


def _build_resource_quotas(limits: dict[str, Any]) -> Optional[dict]:
    """Forward Waldur ResourceProject.limits as the operator's resourceQuotas.

    Pass-through. The CRD expects a Waldur-domain dict
    (``cpu`` in millicores, ``memory`` / ``storage`` as K8s quantity
    strings, ``gpu`` as integer count); the operator handles the
    translation to a K8s ResourceQuota object. Keys outside
    ``{cpu, memory, storage, gpu}`` are dropped here (with no error)
    since the operator would discard them anyway with a warning.
    """
    if not limits:
        return None
    out = {k: v for k, v in limits.items() if k in _WALDUR_QUOTA_KEYS and v not in (None, "", 0)}
    if not out:
        return None
    return out
