"""Translate Waldur (Resource, ResourceProject, [UserRole]) into a ManagedRancherProject CR spec.

Pure functions only — no I/O. The backend module wires this into the
Kubernetes client and the Waldur API client.
"""

from string import Template
from typing import Any, Optional

CRD_API_VERSION = "waldur.io/v1alpha1"
CRD_KIND = "ManagedRancherProject"
CRD_PLURAL = "managedrancherprojects"
CRD_SHORT_PLURAL = "mrp"

# Kubernetes object names: max 253 chars (RFC 1123 subdomain).
MAX_K8S_NAME_LENGTH = 253
# We reserve 9 chars for "-" + 8-hex UUID prefix in the truncation path.
NAME_SUFFIX_RESERVE = 9


def cr_name(resource_slug: str, resource_project_uuid: str) -> str:
    """Build the metadata.name for a ManagedRancherProject CR.

    Format: ``<resource.slug>-<rp.uuid[:8]>``. Both inputs are
    immutable in Waldur, so the CR identity is stable across renames.
    The 8-char UUID prefix gives ~4 billion combinations per resource
    — collision-free in practice.

    Resource slugs are auto-generated by Waldur and already RFC-1123
    compliant; we lowercase + truncate defensively.
    """
    safe = resource_slug.lower().strip("-")
    suffix = resource_project_uuid.replace("-", "")[:8]
    name = f"{safe}-{suffix}"
    if len(name) > MAX_K8S_NAME_LENGTH:
        # Truncate the slug, never the suffix — keep identity stable.
        name = f"{safe[: MAX_K8S_NAME_LENGTH - NAME_SUFFIX_RESERVE]}-{suffix}"
    return name


def render_group_name(
    template: str,
    *,
    cluster_id: str,
    role_name: str,
    rp_uuid: str = "",
    project_name: str = "",
) -> str:
    """Render a Keycloak group name template.

    Supports four template variables:

    - ``${cluster_id}`` — the Rancher cluster ID this CR targets
    - ``${role_name}`` — the Waldur role name (pre-mapping)
    - ``${rp_uuid}``   — the Waldur ResourceProject UUID (32-char hex)
    - ``${project_name}`` — the human-readable project name

    The default template (set in :func:`build_cr_spec`) includes
    ``${rp_uuid}`` so each (cluster x project x role) triple gets its
    OWN group. Without ``${rp_uuid}`` (or some equivalent per-project
    discriminator), N CRs sharing a (cluster, role) pair would all
    reference the same Keycloak group, and:

    - the operator's per-CR member-sync would thrash that group as it
      processed each CR in turn, AND
    - because Rancher binds the SAME group to N project PRTBs,
      granting a user role on project A would also grant the same
      role on B, C, … — collapsing per-project access into per-cluster.

    Custom templates that omit a per-project token are technically
    accepted (the renderer just substitutes whatever variables it
    knows), but the resulting CRs will collide as above. Stick with
    the default unless you have a strong reason.
    """
    return Template(template).safe_substitute(
        cluster_id=cluster_id,
        role_name=role_name,
        rp_uuid=rp_uuid,
        project_name=project_name,
    )


def build_role_bindings(
    user_roles: list[dict],
    *,
    cluster_id: str,
    group_name_template: str,
    role_map: dict[str, str],
    keycloak_use_user_id: bool = True,
    rp_uuid: str = "",
    project_name: str = "",
) -> list[dict]:
    """Group UserRoles by role name and emit one roleBinding per group.

    ``user_roles`` is a list of dicts shaped like the Waldur
    ``marketplace_provider_resources_team_list`` response — each entry
    must have ``role_name`` and a user identifier (``user_uuid`` or
    ``user_username``).

    Roles that aren't present in ``role_map`` are skipped with no error
    — the operator can't bind them anyway. Caller may log this.

    ``rp_uuid`` and ``project_name`` are passed through to the group
    name template so the rendered group name can be unique per RP
    (recommended -- see :func:`render_group_name` docstring).
    """
    by_role: dict[str, list[dict]] = {}
    for ur in user_roles:
        role = ur.get("role_name")
        if not role or role not in role_map:
            continue
        by_role.setdefault(role, []).append(ur)

    bindings: list[dict] = []
    for role_name in sorted(by_role):
        members = [
            {
                "userIdentifier": ident,
                "lookupByID": keycloak_use_user_id,
            }
            for ur in by_role[role_name]
            if (
                ident := (
                    ur.get("user_uuid") if keycloak_use_user_id else ur.get("user_username")
                )
            )
        ]
        if not members:
            continue
        bindings.append(
            {
                "groupName": render_group_name(
                    group_name_template,
                    cluster_id=cluster_id,
                    role_name=role_name,
                    rp_uuid=rp_uuid,
                    project_name=project_name,
                ),
                "rancherRole": role_map[role_name],
                "members": members,
            },
        )
    return bindings


def build_cr_spec(
    *,
    resource: dict,
    resource_project: dict,
    user_roles: list[dict],
    backend_settings: dict,
) -> dict[str, Any]:
    """Assemble the full CR body (apiVersion + kind + metadata + spec).

    Caller is responsible for setting metadata.namespace from config
    when invoking the K8s API.

    Cluster ID resolution: each Waldur Resource is 1:1 with a Rancher
    downstream cluster, so ``resource["backend_id"]`` IS the cluster
    ID. A resource with an empty ``backend_id`` is a configuration
    bug (the offering owner forgot to set the cluster); raise
    KeyError rather than silently emitting an invalid CR.
    """
    cluster_id = resource.get("backend_id")
    if not cluster_id:
        msg = (
            f"Cannot determine cluster_id for CR: resource "
            f"'{resource.get('slug') or resource.get('uuid')}' has empty "
            "backend_id. Set the Rancher cluster ID as the resource's "
            "backend_id (each Waldur Resource = one Rancher cluster)."
        )
        raise KeyError(msg)

    rp_uuid = resource_project.get("uuid", "")
    project_name = resource_project.get("name", "")

    parent_group = render_group_name(
        backend_settings.get("parent_group_name", "c_${cluster_id}"),
        cluster_id=cluster_id,
        role_name="",
    )
    # Default child template includes ${rp_uuid} so each (cluster x
    # project x role) gets its own Keycloak group -- see
    # render_group_name docstring for why.
    group_template = backend_settings.get(
        "group_name_template", "c_${cluster_id}_${rp_uuid}_${role_name}"
    )
    role_map = backend_settings.get("role_map", {})

    # cr_name is reused as the CR's metadata.name so the
    # (resource, resource-project) identity is encoded in one stable
    # place; pull_resource uses it to look the CR back up by name.
    cr_metadata_name = cr_name(resource["slug"], rp_uuid)

    # spec.namespace was removed in operator 0.3.0 -- the operator no
    # longer creates or owns downstream namespaces. Namespace lifecycle
    # is now a user concern via Rancher; do NOT re-add this field
    # without first restoring namespace handling on the operator side.
    spec: dict[str, Any] = {
        "clusterId": cluster_id,
        "projectName": resource_project["name"],
        "resourceUuid": resource["uuid"],
        "resourceProjectUuid": rp_uuid,
        "keycloak": {
            "enabled": True,
            "parentGroupName": parent_group,
            "roleBindings": build_role_bindings(
                user_roles,
                cluster_id=cluster_id,
                group_name_template=group_template,
                role_map=role_map,
                keycloak_use_user_id=backend_settings.get("keycloak_use_user_id", True),
                rp_uuid=rp_uuid,
                project_name=project_name,
            ),
        },
    }

    quotas = _build_resource_quotas(resource_project.get("limits") or {})
    if quotas:
        spec["resourceQuotas"] = quotas

    description = resource_project.get("description")
    if description:
        spec["description"] = description

    return {
        "apiVersion": CRD_API_VERSION,
        "kind": CRD_KIND,
        "metadata": {
            "name": cr_metadata_name,
            # Labels enable orphan-CR pruning in pull_resource: when
            # an RP is removed from Waldur, its CR no longer matches
            # the current set of expected names but is still selectable
            # by the resource-uuid label.
            "labels": {
                "waldur.io/resource-uuid": resource["uuid"],
                "waldur.io/resource-project-uuid": resource_project["uuid"],
            },
        },
        "spec": spec,
    }


_WALDUR_QUOTA_KEYS = {"cpu", "memory", "storage", "gpu"}


def _build_resource_quotas(limits: dict[str, Any]) -> Optional[dict]:
    """Forward Waldur ResourceProject.limits as the operator's resourceQuotas.

    Pass-through. The CRD expects a Waldur-domain dict
    (``cpu`` in millicores, ``memory`` / ``storage`` as K8s quantity
    strings, ``gpu`` as integer count); the operator handles the
    translation to a K8s ResourceQuota object. Keys outside
    ``{cpu, memory, storage, gpu}`` are dropped here (with no error)
    since the operator would discard them anyway with a warning.
    """
    if not limits:
        return None
    out = {k: v for k, v in limits.items() if k in _WALDUR_QUOTA_KEYS and v not in (None, "", 0)}
    if not out:
        return None
    return out
